---

- name: Install dbus
  openbsd_pkg:
    name: "{{ dbus_package }}"
    state: present

- name: Install libxml for xmllint
  openbsd_pkg:
    name: libxml
    state: present

- name: Enable dbus
  service:
    name: "{{ dbus_service }}"
    enabled: yes
