---

- name: Install dbus
  apt:
    name: "{{ dbus_package }}"
    state: present

- name: Install libxml2 for xmllint
  apt:
    name: libxml2-utils
    state: present

- name: Enable dbus
  service:
    name: "{{ dbus_service }}"
    enabled: yes
