---
# tasks file for ansible-role-dbus

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create system-local.conf
  template:
    src: system-local.conf.j2
    dest: "{{ dbus_conf_file }}"
    validate: xmllint --noout %s
  notify: Restart dbus

- name: Start dbus
  service:
    name: "{{ dbus_service }}"
    enabled: true
    state: started
